### ISSUE TITLE
点击播放无法唤起Mpv(Manjaro系统)

### ISSUE THREAD

**Issue by erowz** [diannaojiang/Bilibili-Playin-Mpv#10]
每一步都是按照流程来的
已安装xdg-open和Mpv.
在运行install.sh时显示：
```
➜  bili sudo sh install.sh 
[sudo] erowz 的密码：
exists xdg-open
exists mpv
install.sh:行21: /root/.local/share/applications/mimeapps.list: 没有那个文件或目录
install.sh:行29: /root/.local/share/applications/playinmpv.desktop: 没有那个文件或目录
```
输出方式选的Mpv,
Dash-h.265、h.264还有AV1格式都试过了
点击播放还是没有反应

**Comment by diannaojiang** [comment]
我写的默认脚本是基于root用户的  这里看到您使用的是个人用户erowz   那21和29行的路径应该把/root 替换为您的个人用户目录  诸如/home/erowz

**Comment by erowz** [comment]
感谢！没有报错了！

不过点击播放还是没有反应
下午我自己查了一下运行下面这一段命令
`xdg-mime default playinmpv.desktop x-scheme-handler/mpv`
可以正常使用了 直接用Mpv播放确实比网页流畅许多

**Comment by Bryan2333** [comment]
默认的安装脚本会把 `x-scheme-handler/mpv` 添加到 `~/.local/share/applications/mimeapps.list` 这个文件里面，但是这个文件位置已经被[遗弃](https://wiki.archlinux.org/title/XDG_MIME_Applications#mimeapps.list)了，现在起作用的是 `~/.config/mimeapps.list`。不知道这边能不能修改一下release里的那个安装脚本。

**Comment by diannaojiang** [comment]
> 默认的安装脚本会把 `x-scheme-handler/mpv` 添加到 `~/.local/share/applications/mimeapps.list` 这个文件里面，但是这个文件位置已经被[遗弃](https://wiki.archlinux.org/title/XDG_MIME_Applications#mimeapps.list)了，现在起作用的是 `~/.config/mimeapps.list`。不知道这边能不能修改一下release里的那个安装脚本。

@Bryan2333 您好 经过测试和各方查证。 mimeapps.list用户文件位置是各发行版自行定义的。本人所使用的RH系发行版目前截至fedora36为止均还仅对`~/.local/share/applications/mimeapps.list`生效。其他发行版如果采用了不同的路径的话可以自行修改安装脚本适配。

**Comment by Bryan2333** [comment]
> > 默认的安装脚本会把 `x-scheme-handler/mpv` 添加到 `~/.local/share/applications/mimeapps.list` 这个文件里面，但是这个文件位置已经被[遗弃](https://wiki.archlinux.org/title/XDG_MIME_Applications#mimeapps.list)了，现在起作用的是 `~/.config/mimeapps.list`。不知道这边能不能修改一下release里的那个安装脚本。
> 
> @Bryan2333 您好 经过测试和各方查证。 mimeapps.list用户文件位置是各发行版自行定义的。本人所使用的RH系发行版目前截至fedora36为止均还仅对`~/.local/share/applications/mimeapps.list`生效。其他发行版如果采用了不同的路径的话可以自行修改安装脚本适配。

这样啊。我刚才去FreeDesktop.org上看了看，`mimeapps.list` 的位置确实已经变为 `~/.config/mimeapps.list` , 而 `~/.local/share/applications/mimeapps.list` 实际上已经被遗弃了，只是为了兼容性还保留着。

![截图 2023-02-05 08-18-50](https://user-images.githubusercontent.com/31512600/216795116-3a7f5165-57fa-49df-9d43-4c38f2198478.png)

可能是还有发行版没有跟进，因为 Manjaro 这类 Arch-based 的发行版更新的快一些。那就不改吧。

**Comment by diannaojiang** [comment]
> > > 默认的安装脚本会把 `x-scheme-handler/mpv` 添加到 `~/.local/share/applications/mimeapps.list` 这个文件里面，但是这个文件位置已经被[遗弃](https://wiki.archlinux.org/title/XDG_MIME_Applications#mimeapps.list)了，现在起作用的是 `~/.config/mimeapps.list`。不知道这边能不能修改一下release里的那个安装脚本。
> > 
> > 
> > @Bryan2333 您好 经过测试和各方查证。 mimeapps.list用户文件位置是各发行版自行定义的。本人所使用的RH系发行版目前截至fedora36为止均还仅对`~/.local/share/applications/mimeapps.list`生效。其他发行版如果采用了不同的路径的话可以自行修改安装脚本适配。
> 
> 这样啊。我刚才去FreeDesktop.org上看了看，`mimeapps.list` 的位置确实已经变为 `~/.config/mimeapps.list` , 而 `~/.local/share/applications/mimeapps.list` 实际上已经被遗弃了，只是为了兼容性还保留着。
> 
> ![截图 2023-02-05 08-18-50](https://user-images.githubusercontent.com/31512600/216795116-3a7f5165-57fa-49df-9d43-4c38f2198478.png)
> 
> 可能是还有发行版没有跟进，因为 Manjaro 这类 Arch-based 的发行版更新的快一些。那就不改吧。

@Bryan2333 嗯  我尝试在发行版上查看这几个环境变量 只有XDG_DATA_DIRS指向/usr/share那个目录，其他env并没有定义。   所以推测可能在发行版上还是通过xdg-open写死的路径，那么在目前的release版本下暂时还没有修改，等后续如果有改变的话我会进行更新。
