### ISSUE TITLE
同 issue#9 视频流正常;音频流报错 property not found

### ISSUE THREAD

**Issue by ghost** [diannaojiang/Bilibili-Playin-Mpv#11]
试了几个视频，都是定义音频参数报错，正常播放视频，报错如下。

https://www.bilibili.com/video/BV1rG411n7qp

![220722_203326](https://user-images.githubusercontent.com/59040858/180440923-1667010a-5644-48a5-bdc6-b32576880a10.png)

**Comment by diannaojiang** [comment]
请提供一下系统环境信息及mpv版本号

**Comment by diannaojiang** [comment]
另外我看您这里是mpv.net  我推测可能是您安装了错误的mpv播放器  其不支持[audio-file](https://mpv.io/manual/master/#options-audio-files)这个参数

**Comment by ghost** [comment]
https://github.com/stax76/mpv.net/issues/471
