### ISSUE TITLE
[Feature]增加软解选项

### ISSUE THREAD

**Issue by Brianwind** [diannaojiang/Bilibili-Playin-Mpv#2]
在通过这种方式播放B站新出的8K视频时，MPV播放器会显示为纯白色（包括控制界面），命令行提示为gpu设备实例已暂停，原因是我的核显不支持8k hevc解码（r7-4800u）。默认输出似乎是硬解，希望增加软解选项

**Comment by diannaojiang** [comment]
这个需要修改mpv的配置文件，不属于本项目的问题。
你可以参考mpv的官方文档：http://mpv.io/manual/master/
