### ISSUE TITLE
linux平台支持

### ISSUE THREAD

**Issue by chenxiex** [diannaojiang/Bilibili-Playin-Mpv#3]
希望开发者能增加linux平台支持（虽然希望渺茫），至少支持linux下编译安装。

**Comment by diannaojiang** [comment]
如果只是编译安装的话倒是可以 因为我发布出来之前就是自己用gcc做的。  但主要是linux上我记得好像没有可以替代application url的特性。所以很难从浏览器唤起本地二进制程序。

**Comment by chenxiex** [comment]
> 如果只是编译安装的话倒是可以 因为我发布出来之前就是自己用gcc做的。 但主要是linux上我记得好像没有可以替代application url的特性。所以很难从浏览器唤起本地二进制程序。

这方面我也不是很了解，但是linux浏览器唤起本地二进制应该是可以的，ff和chrome都有这个功能。像是百度网盘网页就支持唤起客户端下载，这个linux下也有效。

**Comment by gqcdm** [comment]
+1

**Comment by Bit0r** [comment]
> 如果只是编译安装的话倒是可以 因为我发布出来之前就是自己用gcc做的。 但主要是linux上我记得好像没有可以替代application url的特性。所以很难从浏览器唤起本地二进制程序。

有这个特性的，Linux平台有xdg-open，只要有.desktop文件就会自动注册

```desktop
[Desktop Entry]
Type=Application
Name=mpv-bilibili
GenericName=Multimedia player
Comment=Play Bilibili videos with MPV
NoDisplay=true
Exec=mpv-bilibili %U
Categories=AudioVideo;Audio;Video;Player;TV;
MimeType=x-scheme-handler/mpv-bilibili;
```
将这个配置放入 `~/applications/mpv-bilibili.desktop`，系统就会自动注册 `mpv-bilibili://`。
想要注册什么类型的`url`，只需要修改`MimeType`就行

**Comment by diannaojiang** [comment]
> 

kde和gnome都支持么？

**Comment by diannaojiang** [comment]
> > 如果只是编译安装的话倒是可以 因为我发布出来之前就是自己用gcc做的。 但主要是linux上我记得好像没有可以替代application url的特性。所以很难从浏览器唤起本地二进制程序。
> 
> 有这个特性的，Linux平台有xdg-open，只要有.desktop文件就会自动注册
> 
> ```desktop
> [Desktop Entry]
> Type=Application
> Name=mpv-bilibili
> GenericName=Multimedia player
> Comment=Play Bilibili videos with MPV
> NoDisplay=true
> Exec=mpv-bilibili %U
> Categories=AudioVideo;Audio;Video;Player;TV;
> MimeType=x-scheme-handler/mpv-bilibili;
> ```
> 
> 将这个配置放入 `~/applications/mpv-bilibili.desktop`，系统就会自动注册 `mpv-bilibili://`。 想要注册什么类型的`url`，只需要修改`MimeType`就行

kde和gnome都支持么？

**Comment by diannaojiang** [comment]
已提供linux平台支持 可以按照使用指南食用  @chenxiex @Bit0r @gqcdm
