### ISSUE TITLE
Cannot read properties of undefined (reading 'url')

### ISSUE THREAD

**Issue by Felrix** [diannaojiang/Bilibili-Playin-Mpv#4]
Bilibili Evolved选择mpv下载视频弹出错误（已经按照食用指南进行操作
Cannot read properties of undefined (reading 'url')

**Comment by diannaojiang** [comment]
是在浏览器网页端提示的错误还是在本地端弹出的exe弹出的url呢

**Comment by Felrix** [comment]
> 是在浏览器网页端提示的错误还是在本地端弹出的exe弹出的url呢

是网页端Bilibili Evolved弹出的

**Comment by diannaojiang** [comment]
那如果你输出方式选择Toast的话他能正常弹出视频url么

**Comment by Felrix** [comment]
> 那如果你输出方式选择Toast的话他能正常弹出视频url么

可以的，正常弹出

**Comment by diannaojiang** [comment]
能麻烦你截图一下toast时正常弹出的url窗口和mpv输出时的错误提示么
已经确认一下你所使用的版本是最新的Bilibili Evolved (Preview)-v2.0.8么

**Comment by diannaojiang** [comment]
然后你安装本插件的方式是通过url添加的还是直接在线搜索得到的呢。 如果是url添加的话可以在设置里删除后使用在线方式再试试。

**Comment by Felrix** [comment]
<img width="1120" alt="image" src="https://user-images.githubusercontent.com/66423087/147413341-7fd37422-05b5-46bd-911b-f49761ec781f.png">
<img width="1120" alt="image" src="https://user-images.githubusercontent.com/66423087/147413354-6b4d02b8-5a7d-4adb-be6a-e01124f3d9b7.png">
久等了
安装这个插件是通过在线仓库的preview分支安装的

**Comment by diannaojiang** [comment]
哦  抱歉 我忘了在说明中写明了   格式要选用 dash h.264或是h.265

**Comment by Felrix** [comment]
> 哦 抱歉 我忘了在说明中写明了 格式要选用 dash h.264或是h.265

终于解决了，原来是不支持flv
