### ISSUE TITLE
注册表操作改善

### ISSUE THREAD

**Issue by Lee-7723** [diannaojiang/Bilibili-Playin-Mpv#5]
bilibili-evolved v1的时候我有过这个想法
https://github.com/the1812/Bilibili-Evolved/discussions/1762
参考了 https://greasyfork.org/zh-CN/scripts/416271-play-with-mpv 这个脚本。

能不能把添加注册表的操作改为用bat实现，这样把文件放到指定位置就直接执行就可以了，无需再改路径

**Comment by diannaojiang** [comment]
你的意思是把bat放到mpv安装路径然后直接运行读取当前路径么？ 一方面是windows对特殊字符路径的处理比较垃圾（
另一方面是我懒。 你要是愿意修改的话欢迎pull一个request

**Comment by diannaojiang** [comment]
1.0的时候我是自己偷偷改bilibilievolved自己用。2.0之后发现提交一个插件维护的话没那么费事就简单整理了下代码丟上来了（

**Comment by Lee-7723** [comment]
那我先自己改一下试试，如果效果还可以就传上来（本人菜，还没用过pull request😥，操作有误的话求轻喷）
