### ISSUE TITLE
想請問是否可以支持potplayer

### ISSUE THREAD

**Issue by XPRAMT** [diannaojiang/Bilibili-Playin-Mpv#6]
MPV我個人用不太習慣，想請問是否能調用potplayer來播放呢

**Comment by diannaojiang** [comment]
抱歉 potplayer 并非一个开源友好的播放软件 而且对部分先进编码和协议也无法支持。 故本项目将不会尝试适配potplayer。希望您可以今早适应mpv的使用习惯或是选用他人对mpv界面的自定义配置
