### ISSUE TITLE
不能兼容最新版本的bilibili evolved，添加插件以后无法在功能内显示

### ISSUE THREAD

**Issue by Silverhza** [diannaojiang/Bilibili-Playin-Mpv#7]

**Comment by diannaojiang** [comment]
刚刚测试
be版本：v2.1.6-preview
无任何问题
本插件需要依赖于“组件-下载视频”
本插件安装后是显示在“Bilibili-Evolved-功能-下载视频-输出方式“内的
请确认使用方式是否有误

**Comment by Silverhza** [comment]
谢谢

**Comment by Silverhza** [comment]
现在可以了，但是有一个问题，调用mpv之后SVP没有工作，请问如何让SVP运行插帧

**Comment by Silverhza** [comment]
这是我的mpv.config
input-ipc-server=/tmp/mpvsocket
hwdec=auto-copy
hwdec-codecs=all
hr-seek-framedrop=no
no-resume-playback
opengl-early-flush=no

**Comment by Silverhza** [comment]
非常感谢 问题解决
