### ISSUE TITLE
点击播放后无法唤起播放器

### ISSUE THREAD

**Issue by lxyer** [diannaojiang/Bilibili-Playin-Mpv#8]
<img width="928" alt="image" src="https://user-images.githubusercontent.com/17336748/174924519-1e438af0-e08d-45b3-b61f-e47c5792ae2b.png">
<img width="1343" alt="image" src="https://user-images.githubusercontent.com/17336748/174924729-71bad546-6f2f-4e79-84f2-03331c4db53c.png">

**Comment by diannaojiang** [comment]
reg里的路径要用双斜杠
